package 練習問題3;

import java.io.IOException;

public class Main {

	public static void main(String[] args) throws IOException{
		// TODO 自動生成されたメソッド・スタブ
		System.out.println("プログラムが起動しました");
		throw new IOException();//例外の実行

	}

}
